export const spotifyEmbeds = [
  {
    id: 'album-2qvA7HmSg1iM6XMiFF76dp',
    label: 'Spotify Album Reference',
    type: 'album',
    spotifyId: '2qvA7HmSg1iM6XMiFF76dp',
    src: 'https://open.spotify.com/embed/album/2qvA7HmSg1iM6XMiFF76dp?utm_source=generator',
    height: 352,
  },
];

export const inceptionSpotifyTracks = [
  {
    id: 'track-7DU7DNVDZouvJ34tPcPxBj',
    label: 'Inception Track Reference 01',
    type: 'track',
    film: 'Inception',
    spotifyId: '7DU7DNVDZouvJ34tPcPxBj',
    src: 'https://open.spotify.com/embed/track/7DU7DNVDZouvJ34tPcPxBj?utm_source=generator',
    height: 152,
  },
  {
    id: 'track-1VCBfWtJOGPV3mtGw8mSlW',
    label: 'Inception Track Reference 02',
    type: 'track',
    film: 'Inception',
    spotifyId: '1VCBfWtJOGPV3mtGw8mSlW',
    src: 'https://open.spotify.com/embed/track/1VCBfWtJOGPV3mtGw8mSlW?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-5xKVYMxOHB2XRLCUafFrz6',
    label: 'Inception Track Reference 03',
    type: 'track',
    film: 'Inception',
    spotifyId: '5xKVYMxOHB2XRLCUafFrz6',
    src: 'https://open.spotify.com/embed/track/5xKVYMxOHB2XRLCUafFrz6?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-7G799Mcsbvfn5TSWZ7u7gI',
    label: 'Inception Track Reference 04',
    type: 'track',
    film: 'Inception',
    spotifyId: '7G799Mcsbvfn5TSWZ7u7gI',
    src: 'https://open.spotify.com/embed/track/7G799Mcsbvfn5TSWZ7u7gI?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-3maMYEbpgp1ttMONc8Wjyr',
    label: 'Inception Track Reference 05',
    type: 'track',
    film: 'Inception',
    spotifyId: '3maMYEbpgp1ttMONc8Wjyr',
    src: 'https://open.spotify.com/embed/track/3maMYEbpgp1ttMONc8Wjyr?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-6s543KncTsc2rJtMd6kJ8v',
    label: '528491',
    type: 'track',
    film: 'Inception',
    spotifyId: '6s543KncTsc2rJtMd6kJ8v',
    src: 'https://open.spotify.com/embed/track/6s543KncTsc2rJtMd6kJ8v?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-77QDBf1zTvyegtTpAO5EpH',
    label: 'Inception Track Reference 07',
    type: 'track',
    film: 'Inception',
    spotifyId: '77QDBf1zTvyegtTpAO5EpH',
    src: 'https://open.spotify.com/embed/track/77QDBf1zTvyegtTpAO5EpH?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-3C12og48CWBrxVV2FK6Dhw',
    label: 'Inception Track Reference 08',
    type: 'track',
    film: 'Inception',
    spotifyId: '3C12og48CWBrxVV2FK6Dhw',
    src: 'https://open.spotify.com/embed/track/3C12og48CWBrxVV2FK6Dhw?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-7ifWgqspqvPpQWXCfyrho4',
    label: 'Inception Track Reference 09',
    type: 'track',
    film: 'Inception',
    spotifyId: '7ifWgqspqvPpQWXCfyrho4',
    src: 'https://open.spotify.com/embed/track/7ifWgqspqvPpQWXCfyrho4?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-3iR6S8t0mOLUZUAB77KgrP',
    label: 'Inception Track Reference 10',
    type: 'track',
    film: 'Inception',
    spotifyId: '3iR6S8t0mOLUZUAB77KgrP',
    src: 'https://open.spotify.com/embed/track/3iR6S8t0mOLUZUAB77KgrP?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-3NVrDGv0eYHeN4M8Abf4UX',
    label: 'Inception Track Reference 11',
    type: 'track',
    film: 'Inception',
    spotifyId: '3NVrDGv0eYHeN4M8Abf4UX',
    src: 'https://open.spotify.com/embed/track/3NVrDGv0eYHeN4M8Abf4UX?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-6ZFbXIJkuI1dVNWvzJzown',
    label: 'Time',
    type: 'track',
    film: 'Inception',
    spotifyId: '6ZFbXIJkuI1dVNWvzJzown',
    src: 'https://open.spotify.com/embed/track/6ZFbXIJkuI1dVNWvzJzown?utm_source=generator',
    height: 352,
  },
];

export const interstellarSpotifyTracks = [
  {
    id: 'track-6pWgRkpqVfxnj3WuIcJ7WP',
    label: 'Cornfield Chase',
    type: 'track',
    film: 'Interstellar',
    spotifyId: '6pWgRkpqVfxnj3WuIcJ7WP',
    src: 'https://open.spotify.com/embed/track/6pWgRkpqVfxnj3WuIcJ7WP?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-1fTAs4YpBA7R21i0iB4j54',
    label: 'Stay',
    type: 'track',
    film: 'Interstellar',
    spotifyId: '1fTAs4YpBA7R21i0iB4j54',
    src: 'https://open.spotify.com/embed/track/1fTAs4YpBA7R21i0iB4j54?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-6GUq9y0Iy5QrAuPYxTrFp2',
    label: 'S.T.A.Y.',
    type: 'track',
    film: 'Interstellar',
    spotifyId: '6GUq9y0Iy5QrAuPYxTrFp2',
    src: 'https://open.spotify.com/embed/track/6GUq9y0Iy5QrAuPYxTrFp2?utm_source=generator',
    height: 352,
  },
  {
    id: 'track-5aaXqH8rgKZxg61HjECldi',
    label: 'No Time for Caution',
    type: 'track',
    film: 'Interstellar',
    spotifyId: '5aaXqH8rgKZxg61HjECldi',
    src: 'https://open.spotify.com/embed/track/5aaXqH8rgKZxg61HjECldi?utm_source=generator',
    height: 352,
  },
];
